### ISSUE TITLE
version string should match other first-party agents

### ISSUE THREAD

**Issue by janxious** [Instrumental/instrumental_agent-python#10]
`version python/instrumental_agent/VERSION`

**Comment by jqr** [comment]
I'll have to dig it up, but we actually have a feature request, now implemented in swagger-codegen, that should cover standardizing this process across all of our swagger agents.

**Comment by janxious** [comment]
This is not a swagger-based client :)

**Comment by jqr** [comment]
Derp, I put that comment in the wrong place 💃
