### ISSUE TITLE
Update package name to instrumental_agent

### ISSUE THREAD

**Issue by jason-o-matic** [Instrumental/instrumental_agent-python#4]
We released this before we discussed how we wanted to name our packages. We should update the package unless there's a good reason not to.

Here's the current: https://pypi.python.org/pypi?name=instrumental-agent&:action=display

**Comment by jqr** [comment]
This package is already called instrumental_agent, see [setup.py](https://github.com/Instrumental/instrumental_agent-python/blob/master/setup.py#L6).

**Comment by jqr** [comment]
BTW, it seems the package management uses a dash in place of an underscore everywhere.
