### ISSUE TITLE
Version sent during hello is inaccurate 

### ISSUE THREAD

**Issue by jqr** [Instrumental/instrumental_agent-python#6]
When sending the `hello` command, the agent can send non-current package versions. It's expected to send the version of the package that is currently in use.

So if you had versions `0.1.0` and `0.2.0` installed, and the application was using `0.2.0` it may send `0.1.0` with `hello` even though version `0.2.0` is the code that is in use.

**Reproducing**:
1. Install `0.1.0`
2. Install `0.2.0`
3. Load `0.1.0` in code, and inspect the `hello` output using `nc` or similar. You should see `version 0.1.0`
4. Load `0.2.0` in code, and inspect the `hello` output using `nc` or similar. You should see `version 0.2.0` but you will likely see `0.1.0` instead.

**Comment by janxious** [comment]
Can you explain that more? Is this a situation where we need to be reading the version from a config, or something different?

**Comment by jqr** [comment]
When I originally wrote the code, I thought I was querying the package database for the installed version. Instead it appears I was querying for _all_ installed versions, and it actually ends up choosing the smallest version on my machine, though I suspect it is non-deterministic.

I've revised the original comment to make it less cryptic.
