### ISSUE TITLE
should not use mktime on utctimetuple

### ISSUE THREAD

**Issue by spacetc62** [Instrumental/instrumental_agent-python#9]
https://github.com/Instrumental/instrumental_agent-python/blob/master/instrumental_agent/agent.py#L27

time.mktime assumes the the time tuple is a _local_ time tuple: https://docs.python.org/2/library/time.html#time.mktime
So by doing this, if the code is running on a non UTC machine, the timestamp that comes out will be incorrect.

since you have a utctimetuple there, what you actually want to use is calendar.timegm:
https://docs.python.org/2/library/calendar.html?highlight=timegm#calendar.timegm

**Comment by jqr** [comment]
Nice catch!
